name: Daily Data Sync
# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  # (to test the worflow straight away)
  workflow_dispatch:
  schedule:
    # Runs every two minutes
    # Note: Use UTC time for schedules
    - cron: '*/1 * * * *'
# A workflow run is made up of one or more jobs that can run sequentially 
# or in parallel
jobs:
  # This workflow contains a single job called "sync-data"
  sync-data:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed 
    # as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, 
      # so your job can access it
      - name: Checkout Repository
        uses: actions/checkout@v4
      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' # Specify your Python version
      # Install Python dependencies (if needed)
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      
      # Run the data synchronization script
      # This script would contain your logic to fetch data from an API,
      # process it, and perhaps store it or commit it back to the repo.
      - name: Run Sync Script
        run: |
          echo "Starting data synchronization..."
          # Replace with your actual script execution command
          python ./scripts/sync_data.py
          echo "Data synchronization finished."
      #(Bonus): Commit changes if the sync script updated files
      - name: Commit updated data
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: Update data via daily sync"



# 0 2 * * *: Run every day at 2:00 AM.
